### ISSUE TITLE
Erro query_async |  Minha base é creative e da esse erro 

### ISSUE THREAD

**Issue by Monteirexx** [hydrusgg/fivem#2]
Coloquei o token, tudo certo, mas quando dou start da esse erro.

Ajuda PF

https://i.imgur.com/FqR80bz.png

**Comment by JesterIruka** [comment]
O exports query_async só foi criado na versão 2.0.0, este script depende que o oxmysql esteja nesta versão, ou superior.
Esta aqui é a mínima recomendada, vou tentar adicionar no fxmanifest assim que possível.

https://github.com/overextended/oxmysql/releases/tag/v2.3.4
