### ISSUE TITLE
Problema de conexão do fivem com site hydrus.gg

### ISSUE THREAD

**Issue by AlemaoGonzaga** [hydrusgg/fivem#4]
Olá estou tendo problemas com esse script criei uma loja pela hydrus.gg onde que configurei tudo certinho discord bot etc...
Script ele está tendo problema para se conectar fivem com o site, onde que faço uma compra pelo site mais na hora de adicionar produto direto no servidor ele não funciona /vip para acessar meus produtos comprados.

**Comment by JesterIruka** [comment]
Olá, /vip não é um comando para acessar produtos comprados, o /vip mostra o tempo que falta para certos benefícios expirarem.

O comando que resgata benefícios é o /store, mas para isso os créditos tem que estar configurados corretamente, sem créditos, o comando não abre.

Eu explico sobre isso no vídeo de introdução, vou deixar anexado logo abaixo desta mensagem.
https://www.youtube.com/watch?v=NAA9X6xpo6w

**Comment by AlemaoGonzaga** [comment]
Fechouu agradeço pelo retorno tava quebrando cabeça ontem tentando resolver esse problema kkkkkk

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AlemaoGonzaga** [comment]
> Olá, /vip não é um comando para acessar produtos comprados, o /vip mostra o tempo que falta para certos benefícios expirarem.
> 
> O comando que resgata benefícios é o /store, mas para isso os créditos tem que estar configurados corretamente, sem créditos, o comando não abre.
> 
> Eu explico sobre isso no vídeo de introdução, vou deixar anexado logo abaixo desta mensagem. https://www.youtube.com/watch?v=NAA9X6xpo6w

-------------------- Resposta -------------------------
Consegui configurar certinho conforme o vídeo porém ele da essa mensagem de erro:  
SCRIPT ERROR: @fiveshop/server/plugins/credits.lua:221: attempt to index a nil valt > 
ref (@fiveshop/server/plugins/credit.lua:221)

Sabe me dizer oque possa ser?

![d52e6afa-4a44-4166-ae2b-b203b84cb936](https://github.com/hydrusgg/fivem/assets/140818137/8a6e244a-cd7c-4fd2-a356-8cd17f3e2c74)

**Comment by JesterIruka** [comment]
Quando o script iniciou, ele identificou sua base como vRP? ou qualquer outra?
O erro parece ser por conta da Proxy não ter sido inicializada, a Proxy é o que faz a loja conversar com a base.

**Comment by AlemaoGonzaga** [comment]
> Quando o script iniciou, ele identificou sua base como vRP? ou qualquer outra? O erro parece ser por conta da Proxy não ter sido inicializada, a Proxy é o que faz a loja conversar com a base.

Quando ensure fiveshop script da essa mensagem de erro:
![image](https://github.com/hydrusgg/fivem/assets/140818137/3675c360-70f0-4c98-b0e5-41104a5cc8c1)

**Comment by JesterIruka** [comment]
A sua versão do oxmysql não é compatível, você precisa da 1.9.0 ou
superior, atualize ele.

https://github.com/overextended/oxmysql

**Comment by AlemaoGonzaga** [comment]
Cara troquei oxmysql e mesmo assim não da ele da erro no sql quando 
vou iniciar há base, não consegue me ajudar pelo discord?
![image](https://github.com/hydrusgg/fivem/assets/140818137/f5f18d28-25cd-4c5c-996a-6e47a0cb4ab3)
![image](https://github.com/hydrusgg/fivem/assets/140818137/f8bf7e4e-94ba-428d-bbdd-e79db275746e)

**Comment by JesterIruka** [comment]
O oxmysql é retrocompativel, então se algo parou de funcionar quando você
atualizou, grandes chances que estava adulterado, neste caso eu não poderei
ajudar.

**Comment by JesterIruka** [comment]
Se por acaso o erro ainda for com a loja, aí sim poderei te ajudar, mas
todos as versões pós 1.9.0 possuem o query_async

**Comment by michelfivem** [comment]
opa queria editar o site da hydrus mas nao estou consguindo achar onde poe a key tipo  pra trocar as cores dos botao e tals

**Comment by JesterIruka** [comment]
> opa queria editar o site da hydrus mas nao estou consguindo achar onde poe a key tipo pra trocar as cores dos botao e tals

A aba de issues é apenas para falar sobre problema do script, que aliás, o seu relato não possui nenhuma informação relevante ou similar ao issue aberto, o site fornece todas as informações para customizá-lo, todas as modificações que você encontrar não necessitaram de ter contato com a plataforma para serem realizadas, por favor busque conhecer mais sobre desenvolvimento web.
